import type { NextPage } from "next";
import Head from "next/head";

import { CharacterInfiniteList } from "../components/character";
import { BtnScrollToTop } from "../components/ui";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Rick and Morty API</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Rick and Morty API</h1>

                <BtnScrollToTop />

                <div>
                    <h2>Personajes</h2>
                    <CharacterInfiniteList charactersURL="https://rickandmortyapi.com/api/character?page=1" />
                </div>
            </main>
        </div>
    );
};

export default Home;
